export const works: IProject[] = [
  {
    id: 1,
    name: "Wiki of myths",
    info: "Небольшой сборник легенд и мифов разных стран. Разработан дизайн с нуля, проект поддерживается.",
    img: "/wiki.webp",
    skill: ["TypeScript", "React", "styled-components"],
    urlDemo: "https://alisa03.github.io/wiki-of-myths/",
    urlCode: "https://github.com/Alisa03/wiki-of-myths",
  },
  {
    id: 2,
    name: "TURBO JUMP TOKEN",
    info: "Turbo Jump Token - многофункциональный токен",
    img: "/tjt.webp",
    skill: ["TypeScript", "Next.js", "wagmi", "RainbowKit", "next-intl"],
    urlDemo: "https://tjt.pro",
  },
  {
    id: 4,
    name: "Hoodie cats",
    info: "Hoodie cats - nft-коллекция",
    img: "/cats.webp",
    skill: ["React", "TypeScript", "scss"],
    urlDemo: "https://hoodie-cats.vercel.app/",
    urlCode: "https://github.com/Alisa03/Hoodie-cats",
  },
  {
    id: 3,
    name: "Best Technology cooking",
    img: "/btc.webp",
    skill: ["React", "TypeScript", "scss", "i18next"],
    urlDemo: "https://btc-umber.vercel.app/",
  },
];
